# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ab1d7ceeaf5af55fcb5a61eeeca6682100641e9ca2f862ed81f6744a4e1a7ad13adb4c343e3efb3d4e89115f03be49dd6b598db6369a261effbda5430dab10c

test:
  secret_key_base: 70809095ed0081bf38e437eb72b4698f8f70b333fe5088eec5806107a77b26227878665c0ab65947bda1a9c3959791530b3089d6d81c74f195950f30232d4f64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
